// T-050 — proves db/schema_v250_guides_video.sql on a REAL Postgres engine (pglite): idempotent, and the security/behaviour rules hold.
// Run: node qa/sql/schema-v250.test.js  (exit 0 = all pass)
const fs = require('fs');
const path = require('path');
const { PGlite } = require('@electric-sql/pglite');

let pass = 0, fail = 0;
const ok = (c, m) => { if (c) pass++; else { fail++; console.log('FAIL:', m); } };
const U = { A: '00000000-0000-4000-8000-00000000000a', B: '00000000-0000-4000-8000-00000000000b', C: '00000000-0000-4000-8000-00000000000c', D: '00000000-0000-4000-8000-00000000000d', E: '00000000-0000-4000-8000-00000000000e' };

(async () => {
  const sql = fs.readFileSync(path.join(__dirname, '..', '..', 'db', 'schema_v250_guides_video.sql'), 'utf8');
  const db = new PGlite();
  // ── minimal stand-ins for what Supabase + earlier migrations provide ──
  await db.exec(`
    create schema auth;
    create role anon; create role authenticated; create role service_role;
    create table auth.users (id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('test.uid', true), '')::uuid $$;
    create function auth.jwt() returns jsonb language sql stable as $$ select jsonb_build_object('is_anonymous', coalesce(nullif(current_setting('test.anon', true), ''), 'false')::boolean) $$;
    grant usage on schema auth to anon, authenticated, service_role;
    grant execute on all functions in schema auth to anon, authenticated, service_role;
    create table public.social_profiles (user_id uuid primary key references auth.users(id), handle text not null unique);
    create table public.social_public_profiles (user_id uuid, handle text, display_name text, avatar_url text);
    create table public.social_follows (follower_id uuid, following_id uuid);
    create table public.social_reactions (target_type text, target_id bigint, user_id uuid);
    create table public.social_comments (target_type text, target_id bigint, user_id uuid);
    create table public.social_video_uploads (guid text, user_id uuid);
    create table public.social_achievements (id bigint generated by default as identity primary key, user_id uuid, title text, images jsonb not null default '[]', date_set date, date_achieved date, created_at timestamptz default now(), message text, video jsonb);
    create table public.social_clar_posts (id bigint generated by default as identity primary key, title text, message text, active boolean not null default true, created_at timestamptz default now());
    alter table public.social_clar_posts enable row level security;   -- as v246 created it
    grant select on public.social_clar_posts to anon, authenticated;
    create table public.engagement_settings (engaged_day_threshold_pct numeric not null default 60);
    insert into public.engagement_settings default values;
    create table public.user_daily_log (user_id uuid, date date, daily_score numeric);
    -- the v246 view exactly as it exists before v250 (so CREATE OR REPLACE proves the column order is compatible)
    create view public.social_achievement_feed as
    select a.id, a.user_id, a.title, a.images, a.date_set, a.date_achieved, a.created_at, pp.handle, pp.display_name, pp.avatar_url,
      (select count(*) from public.social_reactions r where r.target_type='achievement' and r.target_id=a.id)::int as cheers,
      exists (select 1 from public.social_reactions r where r.target_type='achievement' and r.target_id=a.id and r.user_id=auth.uid()) as i_cheered,
      a.message, (select count(*) from public.social_comments c where c.target_type='achievement' and c.target_id=a.id)::int as comments, a.video
    from public.social_achievements a join public.social_public_profiles pp on pp.user_id=a.user_id where auth.uid() is not null;
    grant usage on schema public to anon, authenticated, service_role;
    insert into auth.users values ('${U.A}'),('${U.B}'),('${U.C}'),('${U.D}'),('${U.E}');
    insert into public.social_profiles values ('${U.A}','alice');
    insert into public.social_public_profiles values ('${U.A}','alice','Alice',null);
  `);
  // ── 1. runs, and runs again (idempotent) ──
  let e1 = null, e2 = null;
  try { await db.exec(sql); } catch (e) { e1 = e; }
  ok(!e1, 'first run: ' + (e1 && e1.message));
  try { await db.exec(sql); } catch (e) { e2 = e; }
  ok(!e2, 'second run (idempotent): ' + (e2 && e2.message));
  if (e1) { console.log('cannot continue'); process.exit(1); }

  const as = async (uid, anon, fn) => { await db.exec(`select set_config('test.uid','${uid || ''}',false); select set_config('test.anon','${anon ? 'true' : 'false'}',false); set role authenticated;`); try { return await fn(); } finally { await db.exec('reset role'); } };
  const asAnon = async fn => { await db.exec(`select set_config('test.uid','',false); set role anon;`); try { return await fn(); } finally { await db.exec('reset role'); } };
  const throws = async p => { try { await p; return false; } catch (e) { return true; } };

  // ── 2. settings ──
  ok((await asAnon(() => db.query('select count(*)::int n from public.app_settings'))).rows[0].n >= 10, 'anon can read app_settings');
  ok(await asAnon(() => throws(db.query("update public.app_settings set num=999 where key='xp_like'"))) || (await db.query("select num from public.app_settings where key='xp_like'")).rows[0].num == 1, 'anon cannot change settings');

  // ── 3. yt_video shape + view column order ──
  ok(!(await throws(db.query(`insert into public.social_achievements (user_id, yt_video) values ('${U.A}', '{"id":"dQw4w9WgXcQ","title":"ok"}')`))), 'valid yt_video accepted');
  ok(await throws(db.query(`insert into public.social_achievements (user_id, yt_video) values ('${U.A}', '{"id":"bad id!","title":"x"}')`)), 'bad yt id rejected');
  ok(await throws(db.query(`insert into public.social_achievements (user_id) values ('${U.A}')`)), 'empty post still rejected');
  const cols = (await db.query("select column_name from information_schema.columns where table_name='social_achievement_feed' order by ordinal_position")).rows.map(r => r.column_name);
  ok(cols[cols.length - 1] === 'yt_video' && cols[cols.length - 2] === 'video', 'yt_video appended last: ' + cols.slice(-3).join(','));

  // ── 4. clar posts scheduling ──
  await db.exec(`insert into public.social_clar_posts (title, publish_at) values ('now', now()), ('future', now() + interval '1 day'), ('expired', now() - interval '2 days');
                 update public.social_clar_posts set expires_at = now() - interval '1 day' where title = 'expired';`);
  const vis = (await asAnon(() => db.query('select title from public.social_clar_posts order by title'))).rows.map(r => r.title);
  ok(vis.length === 1 && vis[0] === 'now', 'only currently-published Clar posts are readable: ' + vis.join(','));

  // ── 5. video signals ──
  ok(!(await as(U.B, false, () => throws(db.query("insert into public.user_video_signals (user_id, video_id, topic, event) values ('" + U.B + "','dQw4w9WgXcQ','x','like')")))), 'own signal ok');
  ok(await as(U.B, false, () => throws(db.query("insert into public.user_video_signals (user_id, video_id, event) values ('" + U.C + "','dQw4w9WgXcQ','like')"))), "cannot write another user's signal");
  ok(await as(U.B, false, () => throws(db.query("insert into public.user_video_signals (user_id, video_id, event) values ('" + U.B + "','dQw4w9WgXcQ','hack')"))), 'invalid event rejected');
  ok((await as(U.C, false, () => db.query('select count(*)::int n from public.user_video_signals'))).rows[0].n === 0, "cannot read another user's signals");

  // ── 6. referrals ──
  const reg = (uid, h, anon) => as(uid, anon, () => db.query('select public.referral_register($1) r', [h])).then(r => r.rows[0].r);
  ok((await reg(U.B, 'alice', true)).reason === 'anonymous', 'anonymous session cannot register a referral');
  ok((await reg(U.A, 'alice', false)).reason === 'self', 'self-referral blocked');
  ok((await reg(U.B, 'nobody', false)).reason === 'no_inviter', 'unknown inviter');
  ok((await reg(U.B, 'alice', false)).ok === true, 'B registers under alice');
  ok((await reg(U.B, 'alice', false)).reason === 'already', 'cannot register twice');
  const claim = uid => as(uid, false, () => db.query('select public.referral_claim() r')).then(r => r.rows[0].r);
  ok((await claim(U.B)).xp === 0 && (await claim(U.A)).xp === 0, 'nothing is paid before the invitee has an engaged day');
  await db.exec(`insert into public.user_daily_log values ('${U.B}', current_date, 0.30)`);
  ok((await claim(U.A)).xp === 0, 'a weak day (30% < 60%) does not qualify');
  await db.exec(`insert into public.user_daily_log values ('${U.B}', current_date - 1, 0.75)`);
  const cB = await claim(U.B); ok(cB.as_invitee === 50, 'invitee gets 50 after an engaged day: ' + JSON.stringify(cB));
  const cA = await claim(U.A); ok(cA.as_inviter === 100, 'inviter gets 100: ' + JSON.stringify(cA));
  ok((await claim(U.A)).xp === 0 && (await claim(U.B)).xp === 0, 'each reward is paid only once');
  // monthly cap
  await db.exec("update public.app_settings set num = 1 where key = 'referral_monthly_cap'");
  await reg(U.C, 'alice', false); await reg(U.D, 'alice', false);
  await db.exec(`insert into public.user_daily_log values ('${U.C}', current_date, 0.9), ('${U.D}', current_date, 0.9)`);
  ok((await claim(U.A)).as_inviter === 0, 'monthly cap (1, already used) blocks further inviter rewards');
  await db.exec("update public.app_settings set num = 50 where key = 'referral_monthly_cap'");
  ok((await claim(U.A)).as_inviter === 200, 'after the cap is lifted the two waiting referrals pay 2 x 100');
  ok((await as(U.C, false, () => db.query('select count(*)::int n from public.referrals'))).rows[0].n === 1, "a member sees only rows they are part of");

  // ── 7. guides ──
  const insGuide = (uid, o) => as(uid, false, () => db.query(
    `insert into public.guides (slug, title, canonical_key, kind, owner_id, blueprint, status) values ($1,$2,$3,$4,$5,'{"topic":"x"}',$6)`,
    [o.slug, o.title || 'My guide', o.key, o.kind || 'user', o.owner === undefined ? uid : o.owner, o.status || 'pending']));
  ok(!(await throws(insGuide(U.B, { slug: 'g-b1', key: 'g_b1' }))), 'member can create a pending guide');
  ok(await throws(insGuide(U.B, { slug: 'g-b2', key: 'g_b2', status: 'active' })), 'member cannot create an ACTIVE guide');
  ok(await throws(insGuide(U.B, { slug: 'g-b3', key: 'g_b3', kind: 'starter' })), 'member cannot create a starter guide');
  ok(await throws(insGuide(U.B, { slug: 'g-b4', key: 'g_b4', owner: U.C })), "member cannot create a guide owned by someone else");
  ok((await as(U.C, false, () => db.query("select count(*)::int n from public.guides where slug='g-b1'"))).rows[0].n === 0, "other members cannot see my pending guide");
  ok((await as(U.B, false, () => db.query("select count(*)::int n from public.guides where slug='g-b1'"))).rows[0].n === 1, 'I can see my own pending guide');
  const starters = (await as(U.C, false, () => db.query("select count(*)::int n from public.guides where kind='starter' and status='active'"))).rows[0].n;
  ok(starters === 5, '5 active starter guides are readable: ' + starters);
  for (let i = 1; i <= 12; i++) { try { await insGuide(U.E, { slug: 'e' + i, key: 'e_key_' + i }); } catch (e) { /* the 11th+ must fail */ } }
  ok((await db.query(`select count(*)::int n from public.guides where owner_id='${U.E}'`)).rows[0].n === 10, 'anti-spam: max 10 guides per member');

  // ── 8. subscriptions, counts, posts, signals, reports ──
  const gid = (await db.query("select id from public.guides where canonical_key='manifestation'")).rows[0].id;
  await as(U.B, false, () => db.query('insert into public.guide_subscriptions (user_id, guide_id, languages) values ($1,$2,$3)', [U.B, gid, ['en', 'hi']]));
  ok((await db.query('select subscribers from public.guides where id=$1', [gid])).rows[0].subscribers === 1, 'subscriber count maintained by trigger');
  ok(await as(U.C, false, () => throws(db.query('insert into public.guide_subscriptions (user_id, guide_id) values ($1,$2)', [U.B, gid]))), "cannot subscribe someone else");
  // PRIVACY: a member's private guide (holds their personal context) is invisible and un-subscribable for everyone else, even when active
  await as(U.B, false, () => db.query("insert into public.guides (slug, title, canonical_key, kind, owner_id, blueprint, status) values ('priv-b','Private one','priv_b','user',$1,'{\"topic\":\"my personal situation\"}','pending')", [U.B]));
  await db.exec("update public.guides set status='active' where slug='priv-b'");
  const privId = (await db.query("select id from public.guides where slug='priv-b'")).rows[0].id;
  ok((await as(U.C, false, () => db.query("select count(*)::int n from public.guides where slug='priv-b'"))).rows[0].n === 0, "an ACTIVE private guide is invisible to other members");
  ok((await as(U.B, false, () => db.query("select count(*)::int n from public.guides where slug='priv-b'"))).rows[0].n === 1, 'its owner still sees it');
  ok(await as(U.C, false, () => throws(db.query('insert into public.guide_subscriptions (user_id, guide_id) values ($1,$2)', [U.C, privId]))), "others cannot subscribe to someone's private guide");
  ok(!(await as(U.B, false, () => throws(db.query('insert into public.guide_subscriptions (user_id, guide_id) values ($1,$2)', [U.B, privId])))), 'the owner can subscribe to their own private guide');
  await db.query("insert into public.guide_posts (guide_id, lang, title, body, dedupe_key) values ($1,'en','Private post','only for the owner here','p1')", [privId]);
  ok((await as(U.C, false, () => db.query('select count(*)::int n from public.guide_posts where guide_id=$1', [privId]))).rows[0].n === 0, "private guide posts are invisible to others");
  ok((await as(U.B, false, () => db.query('select count(*)::int n from public.guide_posts where guide_id=$1', [privId]))).rows[0].n === 1, "and visible to the owner");
  // private keys are only unique per owner; public keys are unique globally
  await as(U.C, false, () => db.query("insert into public.guides (slug, title, canonical_key, kind, owner_id, blueprint, status) values ('priv-c','Also private','priv_b','user',$1,'{\"topic\":\"x\"}','pending')", [U.C]));
  ok(true, 'two members may both have a private guide with the same topic key');
  ok(await as(U.C, false, () => throws(db.query("insert into public.guides (slug, title, canonical_key, kind, owner_id, blueprint, status, visibility) values ('pub-dup','Dup','manifestation','user',$1,'{}','pending','public')", [U.C]))), 'a second PUBLIC guide on an existing topic key is refused (join the existing one)');
  await db.query(`insert into public.guide_posts (guide_id, lang, title, body, dedupe_key) values ($1,'en','Hello there','A useful little body of text.','k1'),($1,'hi','Namaste','Kuch upyogi baatein.','k1')`, [gid]);
  ok((await as(U.C, false, () => db.query('select count(*)::int n from public.guide_posts'))).rows[0].n === 2, 'members can read published posts of active guides');
  ok(await as(U.C, false, () => throws(db.query("insert into public.guide_posts (guide_id, title, body, dedupe_key) values ('" + gid + "','Hack','hack hack hack hack','z')"))), 'members cannot write posts');
  ok(await throws(db.query(`insert into public.guide_posts (guide_id, lang, title, body, dedupe_key) values ('${gid}','en','Dup','duplicate body text here','k1')`)), 'duplicate (guide,lang,dedupe_key) rejected');
  const pid = (await db.query("select id from public.guide_posts where lang='en' limit 1")).rows[0].id;
  await as(U.B, false, () => db.query("insert into public.guide_signals (user_id, post_id, event) values ($1,$2,'like')", [U.B, pid]));
  ok(await as(U.B, false, () => throws(db.query("insert into public.guide_signals (user_id, post_id, event) values ($1,$2,'like')", [U.B, pid]))), 'a like is stored once');
  ok(await as(U.C, false, () => throws(db.query("insert into public.guide_signals (user_id, post_id, event) values ($1,$2,'like')", [U.B, pid]))), "cannot write someone else's signal");
  // reports → auto-pause at 3 distinct reporters
  const rep = uid => as(uid, false, () => db.query("insert into public.guide_reports (post_id, guide_id, user_id, reason) values ($1,$2,$3,'false_info')", [pid, gid, uid]));
  await rep(U.A); await rep(U.B);
  ok((await db.query('select status from public.guides where id=$1', [gid])).rows[0].status === 'active', '2 reports: still active');
  ok(await as(U.A, false, () => throws(db.query("insert into public.guide_reports (post_id, guide_id, user_id, reason) values ($1,$2,$3,'spam')", [pid, gid, U.A]))), 'one report per member per post');
  await rep(U.C);
  const g2 = (await db.query('select status, reports_open from public.guides where id=$1', [gid])).rows[0];
  ok(g2.status === 'paused' && g2.reports_open === 3, '3 distinct reporters auto-pause the guide: ' + JSON.stringify(g2));
  ok((await as(U.D, false, () => db.query('select count(*)::int n from public.guide_posts'))).rows[0].n === 0, 'paused guide posts are no longer readable');
  ok(await as(U.D, false, () => throws(db.query("update public.guides set status='active' where id=$1", [gid]))) || (await db.query('select status from public.guides where id=$1', [gid])).rows[0].status === 'paused', 'members cannot un-pause a guide');

  // ── 9. sources are private ──
  ok(await as(U.B, false, () => throws(db.query('select * from public.guide_sources'))), 'guide_sources is service-only');
  ok((await db.query('select count(*)::int n from public.guide_sources')).rows[0].n >= 8, 'source allowlist seeded');

  console.log(`schema v250: ${pass} passed, ${fail} failed`);
  process.exit(fail ? 1 : 0);
})().catch(e => { console.error('CRASH', e); process.exit(2); });
