// T-069 / T-070 (B8) — proves db/schema_v253_b8.sql on a REAL Postgres engine (pglite): idempotent; weekly leagues (join, cohorts of 20, ranking by XP GAINED this week,
// privacy masking, blocks, cheers, weekly close with promotion/demotion) and notifications (trigger-created rows, RLS, column-level permissions).
// Run: node qa/sql/schema-v253.test.js  (exit 0 = all pass)
const fs = require('fs'), path = require('path');
const { PGlite } = require('@electric-sql/pglite');

let pass = 0, fail = 0;
const ok = (c, m) => { if (c) pass++; else { fail++; console.log('FAIL:', m); } };
const id = n => '00000000-0000-4000-8000-' + String(n).padStart(12, '0');

(async () => {
  const sql = fs.readFileSync(path.join(__dirname, '..', '..', 'db', 'schema_v253_b8.sql'), 'utf8');
  const db = new PGlite();
  await db.exec(`
    create schema auth;
    create role anon; create role authenticated; create role service_role;
    create table auth.users (id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('test.uid', true), '')::uuid $$;
    grant usage on schema auth to anon, authenticated, service_role;
    grant execute on all functions in schema auth to anon, authenticated, service_role;
    grant usage on schema public to anon, authenticated, service_role;
    create table public.social_profiles (user_id uuid primary key references auth.users(id), handle text not null unique, display_name text not null, avatar_url text, visibility jsonb not null default '{}', xp int not null default 0);
    create table public.social_follows (follower_id uuid not null references auth.users(id), following_id uuid not null references auth.users(id), primary key (follower_id, following_id));
    create table public.social_blocks (blocker_id uuid not null, blocked_id uuid not null, primary key (blocker_id, blocked_id));
    create table public.social_achievements (id bigint generated by default as identity primary key, user_id uuid not null, title text);
    create table public.social_reactions (target_type text not null, target_id bigint not null, user_id uuid not null, primary key (target_type, target_id, user_id));
    create table public.social_comments (id bigint generated by default as identity primary key, target_type text not null, target_id bigint not null, user_id uuid not null, body text not null);
    create table public.youtube_topic_cache (topic text, video_id text, primary key (topic, video_id));
  `);
  // 40 users; profile visibility.leaderboard=true for all but #9 (who chose not to be on the board)
  for (let n = 1; n <= 40; n++) {
    await db.exec(`insert into auth.users values ('${id(n)}');
      insert into public.social_profiles (user_id, handle, display_name, visibility, xp) values ('${id(n)}', 'user${n}', 'User ${n}', '${JSON.stringify({ leaderboard: n !== 9 })}', ${n * 100});`);
  }
  let e1 = null, e2 = null;
  try { await db.exec(sql); } catch (e) { e1 = e; }
  ok(!e1, 'first run: ' + (e1 && e1.message));
  try { await db.exec(sql); } catch (e) { e2 = e; }
  ok(!e2, 'second run (idempotent): ' + (e2 && e2.message));
  if (e1) { console.log('cannot continue'); process.exit(1); }

  const as = async (uid, fn) => { await db.exec(`select set_config('test.uid','${uid || ''}',false); set role authenticated;`); try { return await fn(); } finally { await db.exec('reset role'); } };
  const asSvc = async fn => { await db.exec(`select set_config('test.uid','',false); set role service_role;`); try { return await fn(); } finally { await db.exec('reset role'); } };
  const asAnon = async fn => { await db.exec(`select set_config('test.uid','',false); set role anon;`); try { return await fn(); } finally { await db.exec('reset role'); } };
  const throws = async p => { try { await p; return false; } catch (e) { return true; } };
  const join = uid => as(uid, () => db.query('select * from public.league_join_me()')).then(r => r.rows);

  // ── week start = Monday (IST) ──
  const ws = (await db.query("select public.league_week_start('2026-09-26 10:00+05:30'::timestamptz) d")).rows[0].d;   // a Saturday
  ok(new Date(ws).getUTCDay() === 1 && String(ws.toISOString ? ws.toISOString() : ws).startsWith('2026-09-21'), 'week starts on the Monday: ' + ws);
  const sun = (await db.query("select public.league_week_start('2026-09-27 23:30+05:30'::timestamptz) d")).rows[0].d;
  const mon = (await db.query("select public.league_week_start('2026-09-28 00:10+05:30'::timestamptz) d")).rows[0].d;
  ok(String(sun.toISOString ? sun.toISOString() : sun).startsWith('2026-09-21') && String(mon.toISOString ? mon.toISOString() : mon).startsWith('2026-09-28'), 'Sunday 23:30 IST is still last week; Monday 00:10 IST is the new week');

  // ── joining ──
  ok((await join(id(9))).length === 0, 'a member who is NOT on the leaderboard is never placed in a league');
  ok(await asAnon(() => throws(db.query('select * from public.league_join_me()'))), 'anon cannot call league_join_me');
  const j1 = await join(id(1));
  ok(j1.length === 1 && j1[0].tier === 0 && /^w\d{4}-\d\d-\d\d-t0-/.test(j1[0].cohort_id), 'first member joins tier 0 in a new cohort: ' + JSON.stringify(j1));
  const j1b = await join(id(1));
  ok(j1b.length === 1 && j1b[0].cohort_id === j1[0].cohort_id, 'joining twice returns the same cohort (idempotent)');
  for (let n = 2; n <= 20; n++) await join(id(n === 9 ? 21 : n)); // 9 is off-board; 21 takes the slot -> members 1..8,10..21 = 20 people
  const size = (await db.query('select cohort_id, count(*)::int n from public.league_members group by 1 order by 2 desc')).rows;
  ok(size[0].n === 20 && size.length === 1, 'the first cohort fills to exactly 20: ' + JSON.stringify(size));
  await join(id(22));
  const size2 = (await db.query('select cohort_id, count(*)::int n from public.league_members group by 1 order by 2 desc')).rows;
  ok(size2.length === 2 && size2[0].n === 20 && size2[1].n === 1, 'the 21st member opens a NEW cohort (never 21 in one)');
  ok((await as(id(1), () => db.query('select * from public.league_members'))).rows.length === 1, 'a member can only read their own league_members row');

  // ── board: ranked by XP GAINED this week (not total), masked, blocks ──
  await db.exec(`update public.social_profiles set xp = xp + 500 where user_id = '${id(3)}';      -- +500 this week
                 update public.social_profiles set xp = xp + 900 where user_id = '${id(7)}';      -- +900 this week (7 is the leader)
                 update public.social_profiles set xp = xp + 50  where user_id = '${id(1)}';`);
  let board = (await as(id(1), () => db.query('select * from public.league_board()'))).rows;
  ok(board.length === 20, 'board shows my whole cohort: ' + board.length);
  ok(board[0].user_id === id(7) && board[0].gain === 900 && board[0].rank === 1, 'ranked by XP gained this week: the +900 member is #1 (not the highest total)');
  ok(board[1].user_id === id(3) && board[1].gain === 500, '#2 gained +500');
  ok(board.find(r => r.is_me).user_id === id(1) && board.find(r => r.is_me).gain === 50, 'my row is flagged and shows my gain');
  ok(board.every(r => r.tier === 0 && typeof r.handle === 'string'), 'every row has display fields and a tier');
  await db.exec(`update public.social_profiles set visibility = '{"leaderboard": false}' where user_id = '${id(5)}'`);
  board = (await as(id(1), () => db.query('select * from public.league_board()'))).rows;
  ok(!board.some(r => r.user_id === id(5)) && board.length === 19, 'a member who left the leaderboard disappears from others\' boards');
  ok((await as(id(5), () => db.query('select * from public.league_board()'))).rows.some(r => r.is_me), 'but still sees their own row');
  await db.exec(`insert into public.social_blocks values ('${id(1)}','${id(12)}')`).catch(() => {});
  board = (await as(id(1), () => db.query('select * from public.league_board()'))).rows;
  ok(!board.some(r => r.user_id === id(12)), 'a blocked member is hidden');
  ok(!(await as(id(12), () => db.query('select * from public.league_board()'))).rows.some(r => r.user_id === id(1)), '...and I am hidden from them (both ways)');
  ok((await as(id(25), () => db.query('select * from public.league_board()'))).rows.length === 0, 'someone who has not joined a league sees an empty board (no leak)');
  ok(await asAnon(() => throws(db.query('select * from public.league_board()'))), 'anon cannot read a board');
  const me = (await as(id(1), () => db.query('select * from public.league_me()'))).rows[0];
  ok(me && me.gain === 50 && me.last_result === null, 'league_me: my gain, no previous week yet');

  // ── cheers ──
  ok((await as(id(1), () => db.query('select public.league_cheer($1) r', [id(3)]))).rows[0].r === true, 'cheer a cohort-mate');
  ok((await as(id(1), () => db.query('select public.league_cheer($1) r', [id(22)]))).rows[0].r === false, 'cannot cheer someone outside my cohort');
  await as(id(1), () => db.query('select public.league_cheer($1)', [id(3)])); // again: no duplicate
  ok((await db.query("select count(*)::int n from public.league_cheers where from_user = $1 and to_user = $2", [id(1), id(3)])).rows[0].n === 1, 'one cheer per person per week');
  ok((await as(id(3), () => db.query("select * from public.user_notifications where kind = 'cheer'"))).rows.length === 1, 'the cheered member gets ONE notification');
  ok((await as(id(1), () => db.query('select * from public.league_board()'))).rows.find(r => r.user_id === id(3)).cheered === true, 'the board shows I already cheered them');

  // ── closing the week: promote top 5 / demote bottom 3 (cohorts of 10+) ──
  // build LAST week's cohort directly: 12 members, tiers 1, gains spread
  const lw = (await db.query('select (public.league_week_start() - 7) d')).rows[0].d;
  const lwStr = lw.toISOString ? lw.toISOString().slice(0, 10) : String(lw).slice(0, 10);
  for (let n = 23; n <= 34; n++) await db.exec(`insert into public.league_members (user_id, week_start, tier, cohort_id, xp_start) values ('${id(n)}', '${lwStr}', 1, 'old-12', 0)`); // members who have NOT joined this week yet
  // xp: user n has xp n*100 (+ bonuses from above); their "gain" last week = xp - 0
  const before = (await db.query(`select user_id, tier from public.league_members where week_start = '${lwStr}' order by user_id`)).rows;
  ok(before.length === 12, 'last week\'s cohort of 12 exists');
  ok(await as(id(1), () => throws(db.query('select public.league_close_week()'))), 'a normal member cannot close the week');
  ok(await asAnon(() => throws(db.query('select public.league_close_week()'))), 'anon cannot close the week');
  const closed = (await asSvc(() => db.query('select public.league_close_week() n'))).rows[0].n;
  ok(closed === 12, 'closing processed the 12 members: ' + closed);
  const res = (await db.query(`select user_id, result, rank_final, xp_final from public.league_members where week_start = '${lwStr}' order by rank_final`)).rows;
  ok(res.slice(0, 5).every(r => r.result === 'promoted'), 'top 5 promoted');
  ok(res.slice(5, 9).every(r => r.result === 'stayed'), 'the middle stays');
  ok(res.slice(9).every(r => r.result === 'demoted') && res.length === 12, 'bottom 3 demoted');
  ok(res[0].xp_final >= res[1].xp_final, 'ranked by gain, highest first');
  ok((await asSvc(() => db.query('select public.league_close_week() n'))).rows[0].n === 0, 'closing again does nothing (idempotent)');
  ok((await db.query("select count(*)::int n from public.user_notifications where kind = 'league'")).rows[0].n === 12, 'every member got a league-result notification');
  // next week's tier follows the result
  const topUser = res[0].user_id, botUser = res[11].user_id;
  const nextTop = await join(topUser), nextBot = await join(botUser);
  ok(nextTop[0] && nextTop[0].tier === 2, 'a promoted member starts next week one tier up (or is already in it): tier ' + (nextTop[0] && nextTop[0].tier));
  ok(nextBot[0] && nextBot[0].tier === 0, 'a demoted member starts next week one tier down: tier ' + (nextBot[0] && nextBot[0].tier));
  // small cohorts: only the winner promotes, nobody demotes
  const lw2 = '2026-08-03';
  await db.exec(`insert into public.league_members (user_id, week_start, tier, cohort_id, xp_start) values ('${id(26)}','${lw2}',2,'tiny',0),('${id(27)}','${lw2}',2,'tiny',0),('${id(28)}','${lw2}',2,'tiny',0)`);
  await asSvc(() => db.query("select public.league_close_week('2026-08-03')"));
  const tiny = (await db.query(`select result from public.league_members where week_start = '${lw2}' order by rank_final`)).rows.map(r => r.result);
  ok(tiny.join() === 'promoted,stayed,stayed', 'a cohort under 6: only the winner promotes, nobody demotes: ' + tiny.join());

  // ── notifications ──
  await db.exec(`insert into public.social_achievements (user_id, title) values ('${id(2)}', 'post by 2')`);
  const postId = (await db.query('select id from public.social_achievements limit 1')).rows[0].id;
  await db.exec(`insert into public.social_reactions values ('achievement', ${postId}, '${id(4)}')`);
  await db.exec(`insert into public.social_reactions values ('achievement', ${postId}, '${id(2)}')`);   // a like on my own post
  await db.exec(`delete from public.social_reactions where user_id = '${id(4)}'; insert into public.social_reactions values ('achievement', ${postId}, '${id(4)}')`); // unlike + like again
  let n2 = (await as(id(2), () => db.query("select * from public.user_notifications where kind = 'like'"))).rows;
  ok(n2.length === 1 && n2[0].actor_id === id(4) && n2[0].target_type === 'achievement' && n2[0].read_at === null, 'a like notifies the owner once (self-like and re-like create nothing more)');
  await db.exec(`insert into public.social_comments (target_type, target_id, user_id, body) values ('achievement', ${postId}, '${id(6)}', 'Great job on this, keep going!')`);
  await db.exec(`insert into public.social_comments (target_type, target_id, user_id, body) values ('achievement', ${postId}, '${id(2)}', 'thanks')`);
  n2 = (await as(id(2), () => db.query("select * from public.user_notifications where kind = 'comment'"))).rows;
  ok(n2.length === 1 && /keep going/.test(n2[0].text), 'a comment notifies the owner with a snippet (own comment: nothing)');
  await db.exec(`insert into public.social_follows values ('${id(8)}','${id(2)}'), ('${id(2)}','${id(2 + 1)}')`);
  n2 = (await as(id(2), () => db.query("select * from public.user_notifications where kind = 'follow'"))).rows;
  ok(n2.length === 1 && n2[0].actor_id === id(8), 'a follow notifies the followed member');
  ok((await as(id(3), () => db.query('select * from public.user_notifications'))).rows.every(r => r.user_id === id(3)), 'members only ever read their own notifications');
  ok((await as(id(15), () => db.query('select * from public.user_notifications'))).rows.length === 0, 'someone with no activity has none');
  // read state: only read_at can be changed, only on own rows
  const nid = n2[0].id;
  ok(!(await as(id(2), () => throws(db.query('update public.user_notifications set read_at = now() where id = $1', [nid])))), 'a member can mark their own notification read');
  ok(await as(id(2), () => throws(db.query("update public.user_notifications set text = 'hacked' where id = $1", [nid]))), 'no other column can be changed by the client');
  ok((await as(id(8), () => db.query('update public.user_notifications set read_at = now() where id = $1', [nid]))).affectedRows === 0, "a member cannot touch someone else's notification");
  ok(await as(id(2), () => throws(db.query("insert into public.user_notifications (user_id, kind, actor_id) values ($1, 'like', $2)", [id(2), id(3)]))), 'a client cannot forge a like/follow notification');
  ok(await as(id(2), () => throws(db.query("insert into public.user_notifications (user_id, kind) values ($1, 'badge')", [id(3)]))), 'a client cannot notify someone else');
  ok(!(await as(id(2), () => throws(db.query("insert into public.user_notifications (user_id, kind, target_type, target_id, text) values ($1, 'badge', 'badge', 'streak7', 'Week Warrior')", [id(2)])))), 'a client CAN add their own badge notification');
  ok(await asAnon(() => throws(db.query('select * from public.user_notifications'))), 'anon cannot read notifications');

  console.log(fail ? 'FAILED ' + fail + ' (passed ' + pass + ')' : 'ALL PASSED (' + pass + ')');
  process.exit(fail ? 1 : 0);
})().catch(e => { console.error('CRASH', e); process.exit(1); });
