-- v184a — fix: notification_rules.id was created as GENERATED ALWAYS AS
-- IDENTITY, which rejects any INSERT/upsert that includes an explicit id
-- value — exactly what editing an existing rule does (the row's own id
-- gets sent back as part of the update), causing:
--   "cannot insert a non-default value into column \"id\""
-- GENERATED BY DEFAULT still auto-generates an id when one isn't given,
-- but allows one to be supplied — which upsert-by-id needs. Existing rows
-- and their ids are untouched by this — it only changes the column's
-- future insert behavior.
--
-- Run this once in the Supabase SQL editor.

ALTER TABLE notification_rules ALTER COLUMN id SET GENERATED BY DEFAULT;
