-- ═══════════════════════════════════════════════════════════════════════════
-- v250 — Video signals/prefs, shared YouTube posts, referrals, admin-scheduled Clar posts, and GUIDES (AI-curated, source-grounded feeds).
-- Run ONCE in the Supabase SQL editor, as ONE script (the editor wraps it in a transaction: a failure leaves nothing half-applied).
-- Idempotent (safe to re-run). Purely ADDITIVE: nothing existing is dropped; two existing objects are extended:
--   * social_achievements (+ yt_video column) and its feed view (yt_video APPENDED LAST — the v244 42P16 trap),
--   * social_clar_posts (+ publish_at / expires_at) and its read policy.
-- Run AFTER schema_v246_video.sql (it extends that view).
--
-- WHAT EACH PART IS FOR
--  1. app_settings        admin-editable numbers (XP caps/values, referral rewards, pause threshold) — public read, service write.
--  2. user_prefs_v250     my languages, topic-affinity score, saved videos (own row only).
--  3. user_video_signals  my per-video events (play/pass50/like/save/share/skip…) — own rows only; the raw material for preference scoring.
--  4. yt_video posts      a member can share a YouTube video into the Community feed (id + title only, validated).
--  5. social_clar_posts   scheduling (publish_at / expires_at).
--  6. referrals           invite tracking + server-side reward calculation (definer RPCs; the client cannot mint XP by itself).
--  7. guides*             guides (bots), subscriptions, posts, signals, reports (3 distinct reporters in 7 days auto-pauses a guide), sources allowlist.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. app_settings ─────────────────────────────────────────────────────────
create table if not exists public.app_settings (
  key        text primary key,
  num        numeric not null,
  note       text,
  updated_at timestamptz not null default now()
);
alter table public.app_settings enable row level security;
drop policy if exists app_settings_read on public.app_settings;
create policy app_settings_read on public.app_settings for select to anon, authenticated using (true);
revoke all on public.app_settings from anon, authenticated;
grant select on public.app_settings to anon, authenticated;
grant all on public.app_settings to service_role;
insert into public.app_settings (key, num, note) values
  ('video_xp_daily_cap',        30,  'max XP awards per day from watching videos past 50%'),
  ('interaction_xp_daily_cap',  50,  'max XP per day from reading/liking/saving/sharing guide + video posts'),
  ('xp_read',                   1,   'XP for reading a guide post (>= read_dwell_seconds in view)'),
  ('xp_like',                   1,   'XP for a like'),
  ('xp_save',                   2,   'XP for a save'),
  ('xp_share',                  3,   'XP for a share'),
  ('read_dwell_seconds',        5,   'seconds a post must be in view to count as read'),
  ('referral_inviter_xp',       100, 'XP to the inviter when the invitee completes their first engaged day'),
  ('referral_invitee_xp',       50,  'welcome XP for the invitee'),
  ('referral_monthly_cap',      50,  'max rewarded referrals per inviter per calendar month'),
  ('guide_reports_pause_at',    3,   'distinct reporters within 7 days that auto-pause a guide')
on conflict (key) do nothing;

-- ── 2. user_prefs_v250 ──────────────────────────────────────────────────────
create table if not exists public.user_prefs_v250 (
  user_id      uuid primary key references auth.users(id) on delete cascade,
  languages    text[] not null default '{en}',
  affinity     jsonb  not null default '{}'::jsonb,
  saved_videos jsonb  not null default '[]'::jsonb,
  updated_at   timestamptz not null default now(),
  constraint up250_size check (pg_column_size(affinity) <= 20000 and pg_column_size(saved_videos) <= 40000),
  constraint up250_langs check (cardinality(languages) between 1 and 8)
);
alter table public.user_prefs_v250 enable row level security;
drop policy if exists up250_own on public.user_prefs_v250;
create policy up250_own on public.user_prefs_v250 for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
revoke all on public.user_prefs_v250 from anon, authenticated;
grant select, insert, update, delete on public.user_prefs_v250 to authenticated;
grant all on public.user_prefs_v250 to service_role;

-- ── 3. user_video_signals ───────────────────────────────────────────────────
create table if not exists public.user_video_signals (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  video_id   text not null,
  topic      text,
  event      text not null,
  created_at timestamptz not null default now(),
  constraint uvs_event check (event in ('play','pass50','complete','skip_fast','replay','like','unlike','save','unsave','share')),
  constraint uvs_vid   check (video_id ~ '^[A-Za-z0-9_-]{11}$'),
  constraint uvs_topic check (topic is null or char_length(topic) <= 80)
);
create index if not exists uvs_user_idx on public.user_video_signals (user_id, created_at desc);
alter table public.user_video_signals enable row level security;
drop policy if exists uvs_own_ins on public.user_video_signals;
drop policy if exists uvs_own_sel on public.user_video_signals;
create policy uvs_own_ins on public.user_video_signals for insert to authenticated with check (user_id = auth.uid());
create policy uvs_own_sel on public.user_video_signals for select to authenticated using (user_id = auth.uid());
revoke all on public.user_video_signals from anon, authenticated;
grant select, insert on public.user_video_signals to authenticated;
grant all on public.user_video_signals to service_role;
grant usage, select on sequence public.user_video_signals_id_seq to authenticated, service_role;

-- ── 4. shared YouTube video posts ───────────────────────────────────────────
alter table public.social_achievements add column if not exists yt_video jsonb;
alter table public.social_achievements drop constraint if exists sach_yt_shape;
alter table public.social_achievements add constraint sach_yt_shape check (
  yt_video is null or (
    jsonb_typeof(yt_video) = 'object'
    and (yt_video->>'id') ~ '^[A-Za-z0-9_-]{11}$'
    and char_length(coalesce(yt_video->>'title','')) <= 140
    and pg_column_size(yt_video) <= 512
  )
);
alter table public.social_achievements drop constraint if exists sach_not_empty;
alter table public.social_achievements add constraint sach_not_empty check (
  (title is not null and char_length(title) > 0)
  or (message is not null and char_length(message) > 0)
  or jsonb_array_length(images) > 0
  or video is not null
  or yt_video is not null
);
create or replace view public.social_achievement_feed as
select
  a.id, a.user_id, a.title, a.images, a.date_set, a.date_achieved, a.created_at,
  pp.handle, pp.display_name, pp.avatar_url,
  (select count(*) from public.social_reactions r where r.target_type='achievement' and r.target_id=a.id)::int as cheers,
  exists (select 1 from public.social_reactions r where r.target_type='achievement' and r.target_id=a.id and r.user_id=auth.uid()) as i_cheered,
  a.message,
  (select count(*) from public.social_comments c where c.target_type='achievement' and c.target_id=a.id)::int as comments,
  a.video,
  a.yt_video
from public.social_achievements a
join public.social_public_profiles pp on pp.user_id = a.user_id
where auth.uid() is not null
  and ( a.user_id = auth.uid()
        or exists (select 1 from public.social_follows f where f.follower_id = auth.uid() and f.following_id = a.user_id));
revoke all on public.social_achievement_feed from anon, public;
grant select on public.social_achievement_feed to authenticated, service_role;

-- ── 5. scheduled Clar posts ─────────────────────────────────────────────────
alter table public.social_clar_posts add column if not exists publish_at timestamptz not null default now();
alter table public.social_clar_posts add column if not exists expires_at timestamptz;
drop policy if exists scp_read on public.social_clar_posts;
create policy scp_read on public.social_clar_posts for select to authenticated, anon
  using (active = true and publish_at <= now() and (expires_at is null or expires_at > now()));

-- ── 6. referrals ────────────────────────────────────────────────────────────
create table if not exists public.referrals (
  id               bigint generated by default as identity primary key,
  inviter_id       uuid not null references auth.users(id) on delete cascade,
  invitee_id       uuid not null unique references auth.users(id) on delete cascade,
  inviter_handle   text not null,
  status           text not null default 'pending',
  created_at       timestamptz not null default now(),
  qualified_at     timestamptz,
  inviter_paid_at  timestamptz,
  invitee_paid_at  timestamptz,
  constraint ref_status check (status in ('pending','qualified')),
  constraint ref_not_self check (inviter_id <> invitee_id)
);
create index if not exists ref_inviter_idx on public.referrals (inviter_id);
alter table public.referrals enable row level security;
drop policy if exists ref_own_sel on public.referrals;
create policy ref_own_sel on public.referrals for select to authenticated using (inviter_id = auth.uid() or invitee_id = auth.uid());
revoke all on public.referrals from anon, authenticated;
grant select on public.referrals to authenticated;
grant all on public.referrals to service_role;
grant usage, select on sequence public.referrals_id_seq to service_role;

create or replace function public._setting(p_key text, p_default numeric) returns numeric
language sql stable security definer set search_path = public as $$
  select coalesce((select num from public.app_settings where key = p_key), p_default)
$$;
revoke all on function public._setting(text, numeric) from public, anon, authenticated;

-- does this user have at least one day whose engagement score crossed the "engaged day" bar?
create or replace function public._has_engaged_day(p_uid uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.user_daily_log d
    where d.user_id = p_uid and d.daily_score is not null
      and d.daily_score * 100 >= coalesce((select engaged_day_threshold_pct from public.engagement_settings limit 1), 60)
  )
$$;
revoke all on function public._has_engaged_day(uuid) from public, anon, authenticated;

-- called by the INVITEE once, after Google sign-in, with the handle from ?ref=
create or replace function public.referral_register(p_handle text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare v_me uuid := auth.uid(); v_inv uuid; v_h text := lower(btrim(coalesce(p_handle, '')));
begin
  if v_me is null then return jsonb_build_object('ok', false, 'reason', 'no_session'); end if;
  if coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) then return jsonb_build_object('ok', false, 'reason', 'anonymous'); end if;
  if v_h !~ '^[a-z0-9_.]{3,20}$' then return jsonb_build_object('ok', false, 'reason', 'bad_handle'); end if;
  select user_id into v_inv from public.social_profiles where handle = v_h;
  if v_inv is null then return jsonb_build_object('ok', false, 'reason', 'no_inviter'); end if;
  if v_inv = v_me then return jsonb_build_object('ok', false, 'reason', 'self'); end if;
  if exists (select 1 from public.referrals where invitee_id = v_me) then return jsonb_build_object('ok', false, 'reason', 'already'); end if;
  insert into public.referrals (inviter_id, invitee_id, inviter_handle) values (v_inv, v_me, v_h);
  return jsonb_build_object('ok', true);
end $$;
revoke all on function public.referral_register(text) from public, anon;
grant execute on function public.referral_register(text) to authenticated;

-- called by anyone on app open: pays what is owed to ME (as invitee and/or inviter) — once each — and returns the XP to add locally
create or replace function public.referral_claim() returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_me uuid := auth.uid(); v_in_xp int := 0; v_out_xp int := 0; v_n int; v_room int; v_paid_month int;
  v_inviter_xp numeric := public._setting('referral_inviter_xp', 100);
  v_invitee_xp numeric := public._setting('referral_invitee_xp', 50);
  v_cap int := public._setting('referral_monthly_cap', 50)::int;
begin
  if v_me is null then return jsonb_build_object('xp', 0); end if;
  -- qualify my pending invitees' rows (server-side check of THEIR real engagement)
  update public.referrals r set status = 'qualified', qualified_at = now()
   where r.status = 'pending' and (r.inviter_id = v_me or r.invitee_id = v_me) and public._has_engaged_day(r.invitee_id);
  -- as invitee: welcome XP once, only after qualification
  update public.referrals set invitee_paid_at = now()
   where invitee_id = v_me and status = 'qualified' and invitee_paid_at is null;
  get diagnostics v_n = row_count;
  v_in_xp := v_n * v_invitee_xp::int;
  -- as inviter: 100 XP per newly qualified invitee, within the monthly cap
  select count(*) into v_paid_month from public.referrals
   where inviter_id = v_me and inviter_paid_at >= date_trunc('month', now());
  v_room := greatest(0, v_cap - v_paid_month);
  with due as (
    select id from public.referrals where inviter_id = v_me and status = 'qualified' and inviter_paid_at is null
    order by qualified_at limit v_room
  )
  update public.referrals r set inviter_paid_at = now() from due where r.id = due.id;
  get diagnostics v_n = row_count;
  v_out_xp := v_n * v_inviter_xp::int;
  return jsonb_build_object('xp', v_in_xp + v_out_xp, 'as_invitee', v_in_xp, 'as_inviter', v_out_xp);
end $$;
revoke all on function public.referral_claim() from public, anon;
grant execute on function public.referral_claim() to authenticated;

-- ── 7. GUIDES ───────────────────────────────────────────────────────────────
create table if not exists public.guide_sources (
  id     bigint generated by default as identity primary key,
  name   text not null,
  url    text not null unique,
  tags   text[] not null default '{}',
  active boolean not null default true,
  constraint gsrc_https check (url ~ '^https://')
);
alter table public.guide_sources enable row level security;
revoke all on public.guide_sources from anon, authenticated;
grant all on public.guide_sources to service_role;
grant usage, select on sequence public.guide_sources_id_seq to service_role;
insert into public.guide_sources (name, url, tags) values
  ('Inc42',                 'https://inc42.com/feed/',                                  '{startup,business,india}'),
  ('YourStory',             'https://yourstory.com/feed',                               '{startup,business,india}'),
  ('TechCrunch Startups',   'https://techcrunch.com/category/startups/feed/',           '{startup,business,funding}'),
  ('Farnam Street',         'https://fs.blog/feed/',                                    '{wisdom,business,thinking}'),
  ('James Clear',           'https://jamesclear.com/feed',                              '{habits,growth,wisdom}'),
  ('Mindful',               'https://www.mindful.org/feed/',                            '{mindfulness,peace,relationships}'),
  ('Positive Psychology',   'https://positivepsychology.com/feed/',                     '{mindfulness,growth,positivity,relationships}'),
  ('Tiny Buddha',           'https://tinybuddha.com/feed/',                             '{relationships,peace,positivity}'),
  ('Greater Good (Berkeley)','https://greatergood.berkeley.edu/site/rss',               '{relationships,positivity,peace,growth}'),
  ('Lifehack',              'https://www.lifehack.org/feed',                            '{habits,growth,positivity}')
on conflict (url) do nothing;

create table if not exists public.guides (
  id             uuid primary key default gen_random_uuid(),
  slug           text not null unique,
  title          text not null,
  description    text not null default '',
  canonical_key  text not null,
  visibility     text not null default 'private',
  kind           text not null default 'user',
  owner_id       uuid references auth.users(id) on delete set null,
  blueprint      jsonb not null,
  languages      text[] not null default '{en}',
  status         text not null default 'pending',
  sensitive      boolean not null default false,
  reports_open   int not null default 0,
  subscribers    int not null default 0,
  posts_per_day  int not null default 2,
  next_run_at    timestamptz not null default now(),
  last_run_at    timestamptz,
  last_error     text,
  created_at     timestamptz not null default now(),
  constraint g_kind   check (kind in ('starter','user')),
  constraint g_vis    check (visibility in ('private','public')),
  constraint g_status check (status in ('pending','active','paused','rejected','retired')),
  constraint g_title  check (char_length(title) between 3 and 80),
  constraint g_desc   check (char_length(description) <= 400),
  constraint g_ppd    check (posts_per_day between 1 and 6),
  constraint g_bp     check (jsonb_typeof(blueprint) = 'object' and pg_column_size(blueprint) <= 8000),
  constraint g_key    check (canonical_key ~ '^[a-z0-9_]{3,60}$'),
  constraint g_langs  check (cardinality(languages) between 1 and 8)
);
create index if not exists guides_status_idx on public.guides (status, next_run_at);
-- PUBLIC guides are de-duplicated by topic ("join the existing one"); PRIVATE guides only need to be unique per owner.
create unique index if not exists guides_key_public on public.guides (canonical_key) where visibility = 'public';
create unique index if not exists guides_key_owner  on public.guides (owner_id, canonical_key) where visibility = 'private';
alter table public.guides enable row level security;
drop policy if exists g_read on public.guides;
drop policy if exists g_ins  on public.guides;
-- a member sees: every ACTIVE public guide, and everything of their own (pending / paused / private).
-- A private guide holds the member's personal context in its blueprint, so nobody else can read it.
create policy g_read on public.guides for select to authenticated
  using ((status = 'active' and visibility = 'public') or owner_id = auth.uid());
create policy g_ins  on public.guides for insert to authenticated
  with check (kind = 'user' and owner_id = auth.uid() and status = 'pending' and subscribers = 0 and reports_open = 0);
revoke all on public.guides from anon, authenticated;
grant select, insert on public.guides to authenticated;
grant all on public.guides to service_role;

-- anti-spam: at most 10 guides per member
create or replace function public.guides_limit_trg() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.kind = 'user' and (select count(*) from public.guides where owner_id = new.owner_id) >= 10 then
    raise exception 'guide limit reached';
  end if;
  return new;
end $$;
drop trigger if exists guides_limit on public.guides;
create trigger guides_limit before insert on public.guides for each row execute function public.guides_limit_trg();

create table if not exists public.guide_subscriptions (
  user_id    uuid not null references auth.users(id) on delete cascade,
  guide_id   uuid not null references public.guides(id) on delete cascade,
  languages  text[] not null default '{en}',
  per_day    int not null default 2,
  created_at timestamptz not null default now(),
  primary key (user_id, guide_id),
  constraint gs_ppd check (per_day between 1 and 6),
  constraint gs_langs check (cardinality(languages) between 1 and 8)
);
alter table public.guide_subscriptions enable row level security;
drop policy if exists gs_own on public.guide_subscriptions;
drop policy if exists gs_sel on public.guide_subscriptions;
drop policy if exists gs_ins on public.guide_subscriptions;
drop policy if exists gs_upd on public.guide_subscriptions;
drop policy if exists gs_del on public.guide_subscriptions;
create policy gs_sel on public.guide_subscriptions for select to authenticated using (user_id = auth.uid());
create policy gs_ins on public.guide_subscriptions for insert to authenticated with check (user_id = auth.uid()
  and exists (select 1 from public.guides g where g.id = guide_id and g.status = 'active' and (g.visibility = 'public' or g.owner_id = auth.uid())));
create policy gs_upd on public.guide_subscriptions for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy gs_del on public.guide_subscriptions for delete to authenticated using (user_id = auth.uid());
revoke all on public.guide_subscriptions from anon, authenticated;
grant select, insert, update, delete on public.guide_subscriptions to authenticated;
grant all on public.guide_subscriptions to service_role;

create or replace function public.guide_subs_count_trg() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op in ('INSERT') then update public.guides set subscribers = subscribers + 1 where id = new.guide_id; end if;
  if tg_op in ('DELETE') then update public.guides set subscribers = greatest(0, subscribers - 1) where id = old.guide_id; end if;
  return null;
end $$;
drop trigger if exists guide_subs_count on public.guide_subscriptions;
create trigger guide_subs_count after insert or delete on public.guide_subscriptions for each row execute function public.guide_subs_count_trg();

create table if not exists public.guide_posts (
  id         bigint generated by default as identity primary key,
  guide_id   uuid not null references public.guides(id) on delete cascade,
  lang       text not null default 'en',
  title      text not null,
  body       text not null,
  why        text,
  sources    jsonb not null default '[]'::jsonb,
  yt_video   jsonb,
  practice   jsonb,
  status     text not null default 'published',
  dedupe_key text not null,
  created_at timestamptz not null default now(),
  unique (guide_id, lang, dedupe_key),
  constraint gp_status check (status in ('published','hidden')),
  constraint gp_title  check (char_length(title) between 3 and 140),
  constraint gp_body   check (char_length(body) between 10 and 1200),
  constraint gp_lang   check (lang ~ '^[a-z]{2,8}$'),
  constraint gp_yt     check (yt_video is null or (yt_video->>'id') ~ '^[A-Za-z0-9_-]{11}$')
);
create index if not exists gp_guide_idx on public.guide_posts (guide_id, lang, created_at desc);
alter table public.guide_posts enable row level security;
drop policy if exists gp_read on public.guide_posts;
create policy gp_read on public.guide_posts for select to authenticated
  using (status = 'published' and exists (select 1 from public.guides g where g.id = guide_id and g.status = 'active' and (g.visibility = 'public' or g.owner_id = auth.uid())));
revoke all on public.guide_posts from anon, authenticated;
grant select on public.guide_posts to authenticated;
grant all on public.guide_posts to service_role;
grant usage, select on sequence public.guide_posts_id_seq to service_role;

create table if not exists public.guide_signals (
  user_id    uuid not null references auth.users(id) on delete cascade,
  post_id    bigint not null references public.guide_posts(id) on delete cascade,
  event      text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id, event),
  constraint gsig_event check (event in ('view','like','save','share','more','less','practice_done'))
);
alter table public.guide_signals enable row level security;
drop policy if exists gsig_own on public.guide_signals;
create policy gsig_own on public.guide_signals for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
revoke all on public.guide_signals from anon, authenticated;
grant select, insert, update, delete on public.guide_signals to authenticated;
grant all on public.guide_signals to service_role;

create table if not exists public.guide_reports (
  id         bigint generated by default as identity primary key,
  post_id    bigint not null references public.guide_posts(id) on delete cascade,
  guide_id   uuid not null references public.guides(id) on delete cascade,
  user_id    uuid not null references auth.users(id) on delete cascade,
  reason     text not null,
  note       text,
  created_at timestamptz not null default now(),
  unique (post_id, user_id),
  constraint gr_reason check (reason in ('false_info','harmful','spam','off_topic')),
  constraint gr_note   check (note is null or char_length(note) <= 300)
);
alter table public.guide_reports enable row level security;
drop policy if exists gr_ins on public.guide_reports;
drop policy if exists gr_sel on public.guide_reports;
create policy gr_ins on public.guide_reports for insert to authenticated with check (user_id = auth.uid());
create policy gr_sel on public.guide_reports for select to authenticated using (user_id = auth.uid());
revoke all on public.guide_reports from anon, authenticated;
grant select, insert on public.guide_reports to authenticated;
grant all on public.guide_reports to service_role;
grant usage, select on sequence public.guide_reports_id_seq to service_role, authenticated;

-- auto-pause: N distinct reporters across the guide's posts within 7 days
create or replace function public.guide_reports_trg() returns trigger language plpgsql security definer set search_path = public as $$
declare v_n int;
begin
  select count(distinct user_id) into v_n from public.guide_reports where guide_id = new.guide_id and created_at > now() - interval '7 days';
  update public.guides set reports_open = v_n,
         status = case when v_n >= public._setting('guide_reports_pause_at', 3)::int and status = 'active' then 'paused' else status end
   where id = new.guide_id;
  return null;
end $$;
drop trigger if exists guide_reports_after on public.guide_reports;
create trigger guide_reports_after after insert on public.guide_reports for each row execute function public.guide_reports_trg();

-- ── starter guides (blueprints are data — edit in admin, no code) ──────────
insert into public.guides (slug, title, description, canonical_key, kind, visibility, blueprint, status, posts_per_day, sensitive) values
 ('clar-daily', 'Clar Daily', 'One small, kind idea a day to keep you moving.', 'clar_daily', 'starter', 'public',
  '{"topic":"daily personal growth","intention":"help people take one small positive step each day","angles":["a tiny habit","a mindset shift","a story of progress","a question to reflect on"],"tone":"warm, simple, encouraging, never preachy","avoid":["medical advice","guarantees","politics"],"source_tags":["habits","growth","positivity"],"wikiquote":[],"youtube":["small daily habits motivation","positive mindset morning"]}'::jsonb, 'active', 2, false),
 ('manifestation', 'Manifestation', 'Clarity, belief and aligned action — from timeless teachers.', 'manifestation', 'starter', 'public',
  '{"topic":"manifestation and clarity of desire","intention":"help people get clear on what they want and act on it with belief","angles":["writing desires clearly","belief and self-image","aligned action","gratitude and focus","handling doubt"],"tone":"calm, grounded, practical","avoid":["guaranteed results","medical advice","get-rich-quick"],"source_tags":["positivity","growth"],"wikiquote":["Napoleon Hill","Neville Goddard","Wallace D. Wattles"],"youtube":["manifestation practice","law of attraction explained"]}'::jsonb, 'active', 2, false),
 ('strategy-wisdom', 'Strategy & Wisdom', 'Chanakya and Sun Tzu, made usable for today.', 'strategy_wisdom', 'starter', 'public',
  '{"topic":"strategy and timeless wisdom (Chanakya Neeti, Art of War)","intention":"turn classic strategy into practical daily judgement","angles":["a principle","how to apply it today","a common mistake","a decision framework"],"tone":"clear, thoughtful, grounded","avoid":["violence advocacy","manipulation tactics against individuals","guarantees"],"source_tags":["wisdom","thinking"],"wikiquote":["Chanakya","Sun Tzu"],"youtube":["chanakya neeti lessons","art of war business lessons"]}'::jsonb, 'active', 2, false),
 ('business-startups', 'Business & Startups', 'Ideas and real stories for people building something.', 'business_startups', 'starter', 'public',
  '{"topic":"business, startups and building a company (India-aware)","intention":"help founders and aspiring founders learn, decide and act","angles":["lesson from a founder","funding basics","a common early mistake","customer focus","execution habit"],"tone":"practical, encouraging, honest about risk","avoid":["financial advice","guaranteed returns","stock tips"],"source_tags":["startup","business","funding","india"],"wikiquote":[],"youtube":["startup founder lessons","how to start a business india"]}'::jsonb, 'active', 2, false),
 ('relationships-peace', 'Relationships & Inner Peace', 'Kinder ways to relate to others — and to yourself.', 'relationships_peace', 'starter', 'public',
  '{"topic":"healthy relationships and inner peace","intention":"help people communicate better, set boundaries kindly and find calm","angles":["a communication skill","a small boundary","self-compassion","a calming practice","understanding another view"],"tone":"gentle, respectful, non-judgemental","avoid":["therapy or diagnosis","medical advice","blaming","guarantees"],"source_tags":["relationships","peace","mindfulness","positivity"],"wikiquote":[],"youtube":["how to communicate better relationships","inner peace practice"]}'::jsonb, 'active', 2, true)
on conflict (canonical_key) where visibility = 'public' do nothing;

notify pgrst, 'reload schema';
