-- ═══════════════════════════════════════════════════════════════════════════
-- v246 (T-003) — Official "Clar" posts, so a brand-new user's Community feed
-- is never empty.
-- Run once in the Supabase SQL editor. Safe to re-run (idempotent).
--
-- DESIGN
--  * A separate, tiny table — NOT a fake user row in social_profiles — so
--    "Clar" can never be confused with (or impersonate) a real person, can't be
--    followed/blocked/reported as a user, and nothing existing is touched.
--  * Anyone signed in (anonymous sessions included, since every app user gets
--    one) may READ active posts. Nobody but service_role (Supabase table editor
--    / SQL editor / a future admin.html tab) may write.
--  * Editable without code: change `title` / `message` / `active` in the
--    Supabase Table Editor and the next feed load shows it.
--  * The client only mixes Clar posts in to fill a thin feed (see index of
--    fetchFeedData in clarvoyance_v246.html), so an active user's own feed is
--    not crowded out by them.
--  * cta_tab is a whitelist enforced by CHECK: which app tab the post's button
--    opens (chat / vibe / goal / self / home / fortune), or null for no button.
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.social_clar_posts (
  id          bigint generated by default as identity primary key,
  title       text,
  message     text,
  image_url   text,
  cta_label   text,
  cta_tab     text,
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  constraint scp_not_empty check (
    (title is not null and char_length(title) > 0) or (message is not null and char_length(message) > 0)
  ),
  constraint scp_title_len   check (title is null or char_length(title) <= 120),
  constraint scp_message_len check (message is null or char_length(message) <= 1200),
  constraint scp_cta_len     check (cta_label is null or char_length(cta_label) <= 30),
  constraint scp_cta_tab     check (cta_tab is null or cta_tab in ('chat','vibe','goal','self','home','fortune')),
  constraint scp_image_https check (image_url is null or image_url ~ '^https://')
);

alter table public.social_clar_posts enable row level security;

drop policy if exists scp_read on public.social_clar_posts;
create policy scp_read on public.social_clar_posts
  for select to authenticated, anon using (active = true);

-- explicit grants (this project's standing gotcha: RLS policies alone are not enough)
revoke all on public.social_clar_posts from anon, authenticated;
grant select on public.social_clar_posts to anon, authenticated;
grant all    on public.social_clar_posts to service_role;
grant usage, select on sequence public.social_clar_posts_id_seq to service_role;

-- ── starter content (only inserted while the table is empty, so re-running never duplicates) ──
-- created_at is spread over past days so the newest reads as "today" and they sort naturally.
insert into public.social_clar_posts (title, message, cta_label, cta_tab, created_at)
select v.title, v.message, v.cta_label, v.cta_tab, now() - v.age
from (values
  ('Welcome to ClarZone ✦',
   'This is a small, kind corner for people who are working on becoming. Share a win, cheer someone on, and let the feed be a reminder that you are not doing this alone.',
   'Talk to Clar', 'chat', interval '1 hour'),
  ('Two minutes is enough',
   'You do not need a perfect routine. One small, honest action today — a few slow breaths, one line written down — beats a big plan you never start.',
   'Try a Vibe card', 'vibe', interval '1 day'),
  ('Say it like it is already true',
   'Pick one thing you are moving toward and describe it in the present tense, as if it is already yours. Notice how your body responds to the words.',
   'Open my goal', 'goal', interval '2 days'),
  ('Small wins count',
   'Finished something today, even something tiny? That counts. Post it here — the fastest way to keep going is to let someone else see you do it.',
   null, null, interval '3 days'),
  ('When you feel stuck',
   'Stuck usually means one feeling is asking to be heard. Tell Clar what is going on — there is no wrong way to start, and no one is grading it.',
   'Talk to Clar', 'chat', interval '4 days'),
  ('Your daily non-negotiables',
   'The things you promise yourself, done even on the low-energy days. They are quiet, and they are how a life actually changes.',
   'Go to Home', 'home', interval '5 days'),
  ('A note on comparison',
   'Everyone here is at a different point on their own path. Cheer freely, compare rarely. Your only real competition is who you were yesterday.',
   null, null, interval '6 days')
) as v(title, message, cta_label, cta_tab, age)
where not exists (select 1 from public.social_clar_posts);

notify pgrst, 'reload schema';
