-- ═══════════════════════════════════════════════════════════════════════════
-- v246 (T-006) — Short videos in Community posts (Bunny Stream).
-- Run once in the Supabase SQL editor. Safe to re-run (idempotent).
-- Run it AFTER schema_v243 + schema_v244 (it extends social_achievements and
-- its feed view). Run as ONE script — the SQL editor wraps it in a transaction,
-- so a failure anywhere leaves nothing half-applied.
--
-- DESIGN
--  * A post's video is stored as `video` jsonb = {"guid":"<bunny video id>","duration":<seconds>}.
--    It stores ONLY the id: the app builds the playback URL itself from a fixed CDN
--    address, so nobody can plant an arbitrary URL in someone else's feed.
--  * `social_video_uploads` is a ledger written ONLY by the upload Worker (service_role)
--    when it mints an upload ticket: which member owns which video guid. Members can
--    read their own rows but never write them.
--  * A trigger refuses to save a post whose video guid is not in that ledger under the
--    same member — so you can't attach someone else's (or a made-up) video.
--  * A video-only post (no text, no photos) is now allowed.
--  * social_achievement_feed gets `video` APPENDED at the very end. CREATE OR REPLACE VIEW
--    can only add columns after the existing ones; inserting earlier shifts positions and
--    errors (42P16) — the exact trap hit in v244.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. ledger of who owns which uploaded video ────────────────────────────
create table if not exists public.social_video_uploads (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null,
  guid       text not null unique,
  created_at timestamptz not null default now(),
  constraint svu_guid_shape check (guid ~ '^[0-9a-fA-F-]{36}$')
);
create index if not exists svu_user_idx on public.social_video_uploads (user_id, created_at desc);
alter table public.social_video_uploads enable row level security;
drop policy if exists "svu own select" on public.social_video_uploads;
create policy "svu own select" on public.social_video_uploads for select to authenticated using (user_id = auth.uid());
revoke all on public.social_video_uploads from anon, authenticated;
grant select on public.social_video_uploads to authenticated;
grant all on public.social_video_uploads to service_role;
grant usage, select on sequence public.social_video_uploads_id_seq to service_role;

-- ── 2. social_achievements: the video column + shape checks ───────────────
alter table public.social_achievements add column if not exists video jsonb;
alter table public.social_achievements drop constraint if exists sach_video_shape;
alter table public.social_achievements add constraint sach_video_shape check (
  video is null or (
    jsonb_typeof(video) = 'object'
    and (video->>'guid') ~ '^[0-9a-fA-F-]{36}$'
    and pg_column_size(video) <= 512
  )
);
-- a post may now be video-only
alter table public.social_achievements drop constraint if exists sach_not_empty;
alter table public.social_achievements add constraint sach_not_empty check (
  (title is not null and char_length(title) > 0)
  or (message is not null and char_length(message) > 0)
  or jsonb_array_length(images) > 0
  or video is not null
);

-- ── 3. ownership check: the guid must be one this member's upload ticket created ──
create or replace function public.sach_video_owner_check() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.video is not null then
    if not exists (
      select 1 from public.social_video_uploads u
      where u.guid = (new.video->>'guid') and u.user_id = new.user_id
    ) then
      raise exception 'video does not belong to this member';
    end if;
  end if;
  return new;
end $$;
drop trigger if exists sach_video_owner_trg on public.social_achievements;
create trigger sach_video_owner_trg before insert or update of video on public.social_achievements
  for each row execute function public.sach_video_owner_check();

-- ── 4. feed view: same as v244, plus `video` appended LAST ────────────────
create or replace view public.social_achievement_feed as
select
  a.id, a.user_id, a.title, a.images, a.date_set, a.date_achieved, a.created_at,
  pp.handle, pp.display_name, pp.avatar_url,
  (select count(*) from public.social_reactions r where r.target_type='achievement' and r.target_id=a.id)::int as cheers,
  exists (select 1 from public.social_reactions r where r.target_type='achievement' and r.target_id=a.id and r.user_id=auth.uid()) as i_cheered,
  a.message,
  (select count(*) from public.social_comments c where c.target_type='achievement' and c.target_id=a.id)::int as comments,
  a.video
from public.social_achievements a
join public.social_public_profiles pp on pp.user_id = a.user_id   -- inherits the block filter
where auth.uid() is not null
  and ( a.user_id = auth.uid()
        or exists (select 1 from public.social_follows f where f.follower_id = auth.uid() and f.following_id = a.user_id));

revoke all on public.social_achievement_feed from anon, public;
grant select on public.social_achievement_feed to authenticated, service_role;

notify pgrst, 'reload schema';
