-- ═══════════════════════════════════════════════════════════════════════════
-- v243 — Goal Items + Community Achievement Sharing (photos first, video later)
-- Run once in the Supabase SQL editor. Safe to re-run (idempotent).
--
-- DESIGN
--  * "Goal Items" are small, individually-trackable goals (distinct from the
--    single Major Definite Goal life-story) — each with its own photos, an
--    achieved tick, and a per-item public/private toggle. They live in
--    user_goal_items (own-row RLS, like every other user_* table) so they
--    sync across devices even before anything is ever shared.
--  * "Achievement posts" (social_achievements) are the separate, explicit
--    act of sharing an achieved goal item into the Community feed with a
--    title + photos. Kept as its own table (not bolted onto v241's
--    social_activity, which is deliberately badge_id-only/no free text) so
--    that existing table's safety guarantee stays true — this is a new,
--    clearly-labeled kind of post, not a quiet expansion of the old one.
--  * social_reactions and social_comments are GENERIC (target_type +
--    target_id), not hardcoded to achievements only — a future post type
--    (e.g. a "reel") reuses both with zero schema change. social_comments
--    ships with a conservative own-rows-only read policy since no UI reads
--    it yet in this version; broaden it (to the same follow/block-aware
--    audience as social_achievement_feed) when comments actually ship.
--  * Same lockdown pattern as every table since v178: explicit service_role
--    grant, explicit authenticated grant, RLS scoped to auth.uid().
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. Goal Items (own-row; not visible to other users directly) ───────────
create table if not exists public.user_goal_items (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  title         text not null check (char_length(title) between 1 and 140),
  images        jsonb not null default '[]'::jsonb,
  date_set      timestamptz not null default now(),
  achieved      boolean not null default false,
  date_achieved timestamptz,
  visibility    text not null default 'private' check (visibility in ('public','private')),
  updated_at    timestamptz not null default now(),
  constraint ugi_images_shape check (jsonb_typeof(images) = 'array' and jsonb_array_length(images) <= 8)
);
create index if not exists ugi_user_idx on public.user_goal_items (user_id, updated_at desc);
alter table public.user_goal_items enable row level security;
drop policy if exists "ugi own select" on public.user_goal_items;
drop policy if exists "ugi own insert" on public.user_goal_items;
drop policy if exists "ugi own update" on public.user_goal_items;
drop policy if exists "ugi own delete" on public.user_goal_items;
create policy "ugi own select" on public.user_goal_items for select to authenticated using (user_id = auth.uid());
create policy "ugi own insert" on public.user_goal_items for insert to authenticated with check (user_id = auth.uid());
create policy "ugi own update" on public.user_goal_items for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "ugi own delete" on public.user_goal_items for delete to authenticated using (user_id = auth.uid());
grant select, insert, update, delete on public.user_goal_items to authenticated;
grant select, insert, update, delete on public.user_goal_items to service_role;
grant usage on sequence user_goal_items_id_seq to authenticated, service_role;

-- ── 2. goal-item-images Storage bucket (same pattern as vision-images, v147) ─
insert into storage.buckets (id, name, public)
  values ('goal-item-images', 'goal-item-images', true)
  on conflict (id) do nothing;

drop policy if exists "Goal item images public read" on storage.objects;
create policy "Goal item images public read"
  on storage.objects for select to public
  using (bucket_id = 'goal-item-images');

drop policy if exists "Goal item images user upload" on storage.objects;
create policy "Goal item images user upload"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'goal-item-images' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "Goal item images user delete" on storage.objects;
create policy "Goal item images user delete"
  on storage.objects for delete to authenticated
  using (bucket_id = 'goal-item-images' and (storage.foldername(name))[1] = auth.uid()::text);

-- ── 3. Achievement posts — explicit share action, title + photos ───────────
create table if not exists public.social_achievements (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  goal_item_id  bigint references public.user_goal_items(id) on delete set null,
  title         text not null check (char_length(title) between 1 and 140),
  images        jsonb not null default '[]'::jsonb,
  date_set      timestamptz,
  date_achieved timestamptz,
  created_at    timestamptz not null default now(),
  constraint sach_images_shape check (jsonb_typeof(images) = 'array' and jsonb_array_length(images) <= 6)
);
create index if not exists sach_user_idx on public.social_achievements (user_id, created_at desc);
alter table public.social_achievements enable row level security;
drop policy if exists "sach own select" on public.social_achievements;
drop policy if exists "sach own insert" on public.social_achievements;
drop policy if exists "sach own delete" on public.social_achievements;
create policy "sach own select" on public.social_achievements for select to authenticated using (user_id = auth.uid());
create policy "sach own insert" on public.social_achievements for insert to authenticated with check (user_id = auth.uid());
create policy "sach own delete" on public.social_achievements for delete to authenticated using (user_id = auth.uid());
grant select, insert, delete on public.social_achievements to authenticated;
grant select, insert, update, delete on public.social_achievements to service_role;
grant usage on sequence social_achievements_id_seq to authenticated, service_role;

-- ── 4. Generic reactions (a "cheer" for ANY future post type, not just
--       achievements — kept separate from v241's social_cheers, which is
--       permanently wired to social_activity only, so that table's shape
--       never has to change) ─────────────────────────────────────────────
create table if not exists public.social_reactions (
  target_type text not null check (target_type in ('achievement')),
  target_id   bigint not null,
  user_id     uuid not null references auth.users(id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (target_type, target_id, user_id)
);
alter table public.social_reactions enable row level security;
drop policy if exists "sr2 own select" on public.social_reactions;
drop policy if exists "sr2 own insert" on public.social_reactions;
drop policy if exists "sr2 own delete" on public.social_reactions;
create policy "sr2 own select" on public.social_reactions for select to authenticated using (user_id = auth.uid());
create policy "sr2 own insert" on public.social_reactions for insert to authenticated with check (user_id = auth.uid());
create policy "sr2 own delete" on public.social_reactions for delete to authenticated using (user_id = auth.uid());
grant select, insert, delete on public.social_reactions to authenticated;
grant select, insert, update, delete on public.social_reactions to service_role;

-- ── 5. Generic comments — SCHEMA ONLY this version, no UI reads/writes it
--       yet. Ships now so a future comments feature (on achievements, and
--       later any other post type) needs zero schema change. Read policy is
--       deliberately narrow (own rows only) until real UI + moderation for
--       comment text is built — broaden then, not before. ────────────────
create table if not exists public.social_comments (
  id          bigint generated by default as identity primary key,
  target_type text not null check (target_type in ('achievement')),
  target_id   bigint not null,
  user_id     uuid not null references auth.users(id) on delete cascade,
  body        text not null check (char_length(body) between 1 and 500),
  created_at  timestamptz not null default now()
);
create index if not exists scom_target_idx on public.social_comments (target_type, target_id, created_at);
alter table public.social_comments enable row level security;
drop policy if exists "scom own select" on public.social_comments;
drop policy if exists "scom own insert" on public.social_comments;
drop policy if exists "scom own delete" on public.social_comments;
create policy "scom own select" on public.social_comments for select to authenticated using (user_id = auth.uid());
create policy "scom own insert" on public.social_comments for insert to authenticated with check (user_id = auth.uid());
create policy "scom own delete" on public.social_comments for delete to authenticated using (user_id = auth.uid());
grant select, insert, delete on public.social_comments to authenticated;
grant select, insert, update, delete on public.social_comments to service_role;

-- ── 6. VIEW: achievement feed (same self+follows+block-filtered shape as
--       v241's social_feed) ────────────────────────────────────────────
create or replace view public.social_achievement_feed as
select
  a.id, a.user_id, a.title, a.images, a.date_set, a.date_achieved, a.created_at,
  pp.handle, pp.display_name, pp.avatar_url,
  (select count(*) from public.social_reactions r where r.target_type='achievement' and r.target_id=a.id)::int as cheers,
  exists (select 1 from public.social_reactions r where r.target_type='achievement' and r.target_id=a.id and r.user_id=auth.uid()) as i_cheered
from public.social_achievements a
join public.social_public_profiles pp on pp.user_id = a.user_id   -- inherits the block filter
where auth.uid() is not null
  and ( a.user_id = auth.uid()
        or exists (select 1 from public.social_follows f where f.follower_id = auth.uid() and f.following_id = a.user_id));

-- ── 7. VIEW: someone's public goal items (for the profile's "Currently
--       Pursuing" / "Goals Achieved" sections — same masking pattern as
--       social_public_profiles, just per-item instead of per-field) ──────
create or replace view public.social_public_goal_items as
select g.id, g.user_id, g.title, g.images, g.date_set, g.achieved, g.date_achieved
from public.user_goal_items g
where g.visibility = 'public'
  and auth.uid() is not null
  and ( g.user_id = auth.uid()
        or not exists (
          select 1 from public.social_blocks b
          where (b.blocker_id = auth.uid() and b.blocked_id = g.user_id)
             or (b.blocked_id = auth.uid() and b.blocker_id = g.user_id)));

revoke all on public.social_achievement_feed  from anon, public;
revoke all on public.social_public_goal_items from anon, public;
grant select on public.social_achievement_feed  to authenticated, service_role;
grant select on public.social_public_goal_items to authenticated, service_role;

notify pgrst, 'reload schema';
